name: lint
on:
  push:
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: true
      - name: go mod download
        run: go mod download
      - name: lint
        uses: golangci/golangci-lint-action@v6 # https://github.com/golangci/golangci-lint-action
        with:
          version: v1.59.1
